version: '3.7'

services:

 init:
  container_name: init
  image: flaski/flaski:latest
  user: root
  volumes:
   - data:/flaski_data/users
  #  - /srv/backup/stats:/backup/stats
  #  - /srv/backup/data/users:/backup/users_data
  #  - /srv/backup/mariadb:/backup/mariadb
  #  - data:/flaski_data/users
  #  - ./:/flaski
   - ~/flaski23/backup/stats:/backup/stats
   - ~/flaski23/backup/users_data:/backup/users_data
   - ~/flaski23/backup/mariadb:/backup/mariadb:ro
  environment:
   FLASK_ENV: init
   RESTORE_DB: 0
   RESTORE_USERS_DATA: 0
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   SECRET_KEY: ${SECRET_KEY}
   REDIS_ADDRESS: redis:6379/0
   REDIS_PASSWORD: ${REDIS_PASSWORD}
   MYSQL_USER: flaski
   MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
   MYSQL_HOST: mariadb
   MYSQL_PORT: 3306
   MAIL_PORT: 587
   MAIL_USE_TLS: 1
   MAIL_PASSWORD: ${MAIL_PASSWORD}
   ADMINS: flaski@age.mpg.de
   MAIL_SERVER: mail.age.mpg.de
   MAIL_USERNAME: flaski@age.mpg.de
  links:
   - mariadb
  depends_on:
   - mariadb

 server:
  container_name: server
  image: flaski/flaski:latest
  restart: always
  volumes:
   - data:/flaski_data/users
  #  - /srv/submissions/:/submissions
  #  - /srv/private/:/flaski_private:ro
  #  - ./:/flaski
   - ~/flaski23/private:/flaski_private:ro
   - ~/flaski23/mpcdf:/mpcdf
   - ~/flaski23/submissions:/submissions
  environment:
   N_WORKERS: 4
   ADMINS: flaski@age.mpg.de
   APP_NAME: flaski
   INSTANCE: backup
   SECRET_KEY: ${SECRET_KEY}
   PRIVATE_APPS: /flaski_private/private.apps.tsv
   APP_URL: https://flaski.age.mpg.de
   FLASK_ENV: production
   LOGS: /var/log/flaski/
   MAIL_PASSWORD: ${MAIL_PASSWORD}
   MAIL_PORT: 587
   MAIL_SERVER: mail.age.mpg.de
   MAIL_USERNAME: flaski@age.mpg.de
   MAIL_USE_TLS: '1'
   MYSQL_HOST: mariadb
   MYSQL_PORT: 3306
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   MYSQL_USER: flaski
   DB_NAME: flaski
   REDIS_ADDRESS: redis:6379/0
   REDIS_PASSWORD: ${REDIS_PASSWORD}
  labels:
   - traefik.http.services.server.loadbalancer.server.port=8000
   - traefik.http.middlewares.server_https.redirectscheme.scheme=https
   - traefik.http.routers.server.entrypoints=web
   - traefik.http.routers.server.rule=Host(`flaski.age.mpg.de`)
   - traefik.http.routers.server.middlewares=server_https@docker
   - traefik.http.routers.server_https.rule=Host(`flaski.age.mpg.de`)
   - traefik.http.routers.server_https.tls=true
   - traefik.http.routers.server_https.entrypoints=websecure
  links:
   - mariadb
   - redis
  depends_on:
   - init
   - mariadb
   - redis

 server3:
  container_name: server3
  image: mpgagebioinformatics/flaski:stable
  restart: always
  volumes:
   - data3:/flaski_data/users
  #  - ~/flaski_23/private3/:/flaski_private:ro
  #  - /srv/private3/:/flaski_private:ro
  environment:
   N_WORKERS: 4
   ADMINS: flaski@age.mpg.de
   APP_NAME: myapp
   APP_TITLE: backup3
   INSTANCE: backup3
   SECRET_KEY: ${SECRET_KEY}
   APP_URL: https://flaski.age.mpg.de/v3
   PAGE_PREFIX: /v3
   FLASK_ENV: production
   MAIL_PASSWORD: ${MAIL_PASSWORD}
   MAIL_PORT: 587
   MAIL_SERVER: mail.age.mpg.de
   MAIL_USERNAME: flaski@age.mpg.de
   MAIL_USE_TLS: '1'
   MYSQL_HOST: mariadb
   MYSQL_PORT: 3306
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   MYSQL_USER: flaski
   DB_NAME: flaski
   REDIS_ADDRESS: redis:6379/0
   REDIS_PASSWORD: ${REDIS_PASSWORD}
  labels:
   - traefik.http.services.server3.loadbalancer.server.port=8000
   - traefik.http.middlewares.server3_https.redirectscheme.scheme=https
   - traefik.http.routers.server3.entrypoints=web
   - traefik.http.routers.server3.rule=Host(`flaski.age.mpg.de`) && PathPrefix(`/v3`)
   - traefik.http.routers.server3.middlewares=server_https@docker
   - traefik.http.routers.server3_https.rule=Host(`flaski.age.mpg.de`) && PathPrefix(`/v3`)
   - traefik.http.routers.server3_https.tls=true
   - traefik.http.routers.server3_https.entrypoints=websecure
  links:
   - mariadb
   - redis
  depends_on:
   - init
   - mariadb
   - redis

 backup:
  container_name: backup
  image: mpgagebioinformatics/myapp-flaski2:latest
  entrypoint: /flaski/services/backup/entrypoint.sh
  depends_on:
   - mariadb
   - init
  volumes:
  #  - /srv/backup/mariadb/:/backup/mariadb
  #  - /srv/backup/data/users/:/backup/users_data
  #  - /srv/backup/data/stats/:/backup/stats
   - ~/flaski23/backup/stats:/backup/stats
   - ~/flaski23/backup/users_data:/backup/users_data
   - ~/flaski23/backup/mariadb:/backup/mariadb:ro
   - data:/flaski_data/users:ro
  environment:
   APP_NAME: flaski
   INSTANCE: backup
   FLASK_ENV: backup
   LOGS: /var/log/flaski/
   MYSQL_HOST: mariadb
   MYSQL_PORT: 3306
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   MYSQL_USER: flaski
   DB_NAME: flaski
  restart: unless-stopped
  links:
   - mariadb

 uploads:
  container_name: uploads
  image: mpgagebioinformatics/myapp-flaski2:latest
  entrypoint: /flaski/services/rsync/entrypoint.sh
  volumes:
   - ~/flaski23/backup/mpcdf/:/mpcdf
   - ~/flaski23/backup/submissions/:/submissions
  #  - /srv/submissions/:/submissions
  #  - /srv/backup/mariadb:/backup/mariadb
  #  - /srv/backup/data/users:/backup/users_data
  environment:
   FLASK_ENV: rsync
   OWNCLOUD_ADDRESS: https://datashare.mpcdf.mpg.de
   OWNCLOUD_USER: g-flaski
   OWNCLOUD_PASS: ${OWNCLOUD_PASS}   
  restart: unless-stopped

 mariadb:
  container_name: mariadb
  image: mariadb:10.5
  restart: always
  volumes:
   - db:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

 redis:
  container_name: redis
  image: redis:5
  restart: always
  command: redis-server --requirepass ${REDIS_PASSWORD}

 reverse-proxy:
  image: traefik:v2.4
  command: 
    - --api.insecure=true
    - --providers.docker=true
    - --entrypoints.websecure.address=:443
    - --entrypoints.web.address=:80
    - --providers.file.filename=/etc/traefik/dynamic_conf/conf.yml
    - --providers.file.watch=true
  ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
  volumes:
    - ~/flaski23/certificates/:/tools/certs
    - ./services/traefik/config.yml:/etc/traefik/dynamic_conf/conf.yml:ro
    - /var/run/docker.sock:/var/run/docker.sock
  labels:
    - traefik.enable=false
  depends_on:
   - server
   - server3

#  nginx:
#   container_name: nginx
#   image: nginx:alpine
#   restart: always
#   ports:
#    - 80:80
#    - 443:443
#   volumes:
#    # prod
#    #  - ./services/nginx/flaski23.conf:/etc/nginx/conf.d/default.conf:rw
#    #  - ~/flaski23/certificates/cert.pem:/certs/cert.pem:ro 
#    #  - ~/flaski23/certificates/key.pem:/certs/key.pem:ro
#    #  - ~/flaski23/certificates/dhparam.pem:/certs/dhparam.pem:ro
#    # dev
#    - ./services/nginx/dev.conf:/etc/nginx/conf.d/default.conf:rw
#    - ~/flaski23/certificates/selfsigned/cert.pem:/certs/cert.pem:ro          
#    - ~/flaski23/certificates/selfsigned/key.pem:/certs/key.pem:ro
#    - ~/flaski23/certificates/dhparam.pem:/certs/dhparam.pem:ro
#   links:
#    - server
#    - server3
#   depends_on:
#    - server
#    - server3

volumes:
 data:
  external: false
 data3:
  external: false
 db:
  external: false

