name: production

on:
  push:
    tags: [ '*.*.*' ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
        CURRENT_TAG=${GITHUB_REF#refs/*/}
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        git clone https://github.com/mpg-age-bioinformatics/flaski.git ${CURRENT_TAG}
        cd ${CURRENT_TAG}
        git checkout ${CURRENT_TAG}
        docker build . --file ./services/server/dockerfiles/Dockerfile --tag docker.io/flaski/flaski:latest
        docker tag docker.io/flaski/flaski:latest docker.io/flaski/flaski:${CURRENT_TAG}
        docker tag docker.io/flaski/flaski:latest docker.io/flaski/flaski:dev

        docker tag docker.io/flaski/flaski:latest docker.io/mpgagebioinformatics/flaski2:latest
        docker tag docker.io/flaski/flaski:dev docker.io/mpgagebioinformatics/flaski2:dev
        docker tag docker.io/flaski/flaski:${CURRENT_TAG} docker.io/mpgagebioinformatics/flaski2:${CURRENT_TAG}
        
        docker push docker.io/flaski/flaski:latest
        docker push docker.io/flaski/flaski:${CURRENT_TAG}
        docker push docker.io/flaski/flaski:dev

        docker push docker.io/mpgagebioinformatics/flaski2:latest
        docker push docker.io/mpgagebioinformatics/flaski2:${CURRENT_TAG}
        docker push docker.io/mpgagebioinformatics/flaski2:dev

    # - name: Log into registry ${{ env.REGISTRY }}
    #   uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
    #   with:
    #     registry: docker.io
    #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     password: ${{ secrets.DOCKER_HUB_TOKEN }}

    # # Extract metadata (tags, labels) for Docker
    # # https://github.com/docker/metadata-action
    # - name: Extract Docker metadata
    #   id: meta
    #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
    #   with:
    #     images: docker.io/flaski/flaski

    # # Build and push Docker image with Buildx (don't push on PR)
    # # https://github.com/docker/build-push-action
    # - name: Build and push Docker image
    #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
    #   with:
    #     context: .
    #     file: ./services/server/dockerfiles/Dockerfile
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }},docker.io/flaski/flaski:dev
    #     labels: ${{ steps.meta.outputs.labels }}

  slackNotification:
    needs: build
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: github_action_bot
        SLACK_CHANNEL: flaski
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "Production build and push completed."

  #


